'use strict';
const test=require('node:test');
test('validated SumRA official2026 classification source drives PDF/warnings without rewriting identity; old sources and invalid records remain closed',t=>{
// Actual native source/display regressions. Mutated records are rejected integrity fixtures, never accepted data.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const W=path.resolve(__dirname,'..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const nativeBytes=fs.readFileSync(W+'/data/taxonomy-history-v3.json'),native=JSON.parse(nativeBytes),sumra=Object.entries(native.records).filter(([,r])=>r.paperId==='conference:iclr:2026:openreview-forum-id:v23Pqcm6qp');assert.equal(sumra.length,2);
const other=Object.entries(native.records).find(([,r])=>r.paperId!==sumra[0][1].paperId),controlled=require(W+'/data/current-page-taxonomy-history-v2.json'),controlledEntry=Object.entries(controlled.records)[0],cases=[...sumra,other,controlledEntry];
const citationApi=require(W+'/assets/js/citation-source.js'),pubFixture=require(W+'/tests/fixtures/classification-v3-public');
const created=[];t.after(()=>{for(const dir of created)fs.rmSync(dir,{recursive:true,force:true});});
function build(mode){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'classification-source-display-')));created.push(dir);fs.mkdirSync(dir+'/layouts/_default',{recursive:true});fs.cpSync(W+'/layouts/partials',dir+'/layouts/partials',{recursive:true});fs.cpSync(W+'/assets/js',dir+'/assets/js',{recursive:true});fs.mkdirSync(dir+'/data');for(const p of fs.readdirSync(W+'/data'))if(p.endsWith('.json'))fs.copyFileSync(W+'/data/'+p,dir+'/data/'+p);
 for(const [rel]of cases){fs.mkdirSync(path.dirname(dir+'/'+rel),{recursive:true});fs.copyFileSync(W+'/'+rel,dir+'/'+rel);}
 // Baseline source fallback has the same independent identity parser. Disable only
 // the classificationSource display field; never modify identity/source records.
 if(mode==='before'){const p=dir+'/layouts/partials/research_metadata.html',text=fs.readFileSync(p,'utf8'),line='{{- if $classificationSource }}{{ $memoValue = merge $memoValue (dict "classificationSource" $classificationSource) }}{{ end -}}\n';assert(text.includes(line));fs.writeFileSync(p,text.replace(line,''));}
 if(mode==='no-v3')fs.unlinkSync(dir+'/data/taxonomy-history-v3.json');
 if(mode==='wrong-source'){const data=JSON.parse(nativeBytes);for(const [rel]of sumra){const r=data.records[rel];r.classificationRecord.source.pdfUrl='https://proceedings.iclr.cc/paper_files/paper/2026/file/unapproved-Paper-Conference.pdf';data.records[rel]=pubFixture.sync(r);}fs.writeFileSync(dir+'/data/taxonomy-history-v3.json',JSON.stringify(data));}
 if(mode==='wrong-page')for(const [rel]of sumra)fs.appendFileSync(dir+'/'+rel,'\n');
 fs.writeFileSync(dir+'/hugo.yaml','baseURL: https://example.test/audio-paper-digest-blog/\nuglyURLs: true\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\nmarkup:\n  goldmark:\n    renderer:\n      unsafe: true\n');fs.writeFileSync(dir+'/layouts/index.html','');fs.writeFileSync(dir+'/layouts/_default/single.html','<script id="meta" type="application/json">{{ partial "research_metadata.html" . | jsonify | safeJS }}</script><script id="citation" type="application/json">{{ partial "citation_source.html" . | jsonify | safeJS }}</script><script id="proof" type="application/json">{{ partial "taxonomy_page_proof.html" . | jsonify | safeJS }}</script><script id="identity" type="application/json">{{ partial "research_source_identity_proof.html" . | jsonify | safeJS }}</script>{{ partial "paper_taxonomy.html" . }}{{ partial "paper_toolbar.html" . }}');
 cp.execFileSync('hugo',['--source',dir,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});const results={};for(const [rel]of cases){const p=dir+'/public/posts/'+path.basename(rel,'.md')+'.html',html=fs.readFileSync(p,'utf8'),extract=id=>JSON.parse(html.match(new RegExp('<script id="'+id+'"[^>]*>([\\s\\S]*?)</script>'))[1]);results[rel]={metadata:extract('meta'),citation:extract('citation'),proof:extract('proof'),identity:extract('identity'),html};}return {dir,results};}
const before=build('before'),after=build('after'),invalid=build('wrong-source'),missing=build('no-v3'),changed=build('wrong-page');
for(const [rel,record]of sumra){const a=after.results[rel],b=before.results[rel];assert.equal(a.proof.classificationContract,'historical-source-taxonomy-classification-v3');assert.deepEqual(a.metadata.classificationSource,record.source);assert.equal(a.metadata.identityEvidenceContract,a.identity.contract);assert.deepEqual(a.metadata.sealedSource,a.identity.source);assert.equal(a.metadata.identityProofSha256,a.identity.proofSha256);assert.equal(a.metadata.identityEvidenceContract,b.metadata.identityEvidenceContract);assert.deepEqual(a.metadata.sealedSource,b.metadata.sealedSource);assert.equal(a.metadata.identityProofSha256,b.metadata.identityProofSha256);assert.equal(a.citation.pdfUrl,record.source.pdfUrl);assert.equal(a.citation.url,record.source.sourceUrl);assert.equal(a.citation.title,record.source.originalTitle);assert.equal(a.citation.sourceVersionWarning,record.source.sourceVersionWarning);assert.equal(a.citation.provenanceDisclosure||'',record.source.provenanceDisclosure);assert.equal(a.citation.arxivId,'');assert(a.html.includes('href="'+record.source.pdfUrl+'"'));assert(a.html.includes(record.source.sourceVersionWarning));assert(!b.citation.pdfUrl.includes('/paper/2026/'));
 const nr=citationApi.normalize(a.citation);assert.equal(nr.pdfUrl,record.source.pdfUrl);for(const out of [citationApi.formatCitation(nr,'bib'),citationApi.formatCitation(nr,'ris'),citationApi.formatReference(nr)]){assert(out.includes(record.source.sourceUrl));assert(out.includes(record.source.sourceVersionWarning));}const pack=citationApi.buildResearchPack(nr,{content:'本站导读文本'});assert(pack.includes(record.source.pdfUrl));assert(pack.includes(record.source.sourceVersionWarning));
 for(const bad of [invalid,missing,changed]){const z=bad.results[rel];assert.equal(z.metadata.classificationSource,undefined);assert.notEqual(z.citation.pdfUrl,record.source.pdfUrl);assert(!z.citation.sourceVersionWarning?.includes('本次分类依据 ICLR 2026'));}
}
for(const [rel]of [other,controlledEntry]){assert.deepEqual(after.results[rel].metadata,before.results[rel].metadata);assert.deepEqual(after.results[rel].citation,before.results[rel].citation);assert.equal(after.results[rel].html,before.results[rel].html);}
assert.equal(Object.keys(native.records).length>=18,true);
});
