'use strict';
// Synthetic new-issuer records below test public integrity only, not new LLM acceptance.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const api=require('../scripts/lib/taxonomy-classification-v3-proof'),profileModule=require('../scripts/lib/taxonomy-v3-profiles'),fixtureApi=require('./fixtures/classification-v3-public');
const repo=path.resolve(__dirname,'..'),digest=x=>crypto.createHash('sha256').update(x).digest('hex'),catalog=require('../data/taxonomy-catalog.json'),snapshot=require('../data/taxonomy-registry.json'),nativeAll=require('../data/taxonomy-history-v3.json');
const old=profileModule.profiles[0],fresh=profileModule.profiles[1];
const native={contract:nativeAll.contract,records:Object.fromEntries(Object.entries(nativeAll.records).filter(([,r])=>r.classificationRecord.protectedDependencySha256==='1db887b14d10647b8770f32f238d6ce3f82dc0b8be86e16bebff749fae538655'))};
function synthetic(){const r=JSON.parse(JSON.stringify(fixtureApi.fixture().record)),c=r.classificationRecord,f=c.fingerprintInputs;
 c.registrySha256=fresh.registrySha256;c.protectedDependencies=JSON.parse(JSON.stringify(Object.values(native.records)[0].classificationRecord.protectedDependencies));c.protectedDependencies.files['scripts/lib/historical-source-taxonomy-classification-v3.js']=fresh.implementationSha256;
 f.projectionSha256=fresh.projectionSha256;for(const[k,name]of Object.entries({implementationSha256:'historical-source-taxonomy-classification-v3',snippetImplementationSha256:'source-evidence-snippets-v3',identityImplementationSha256:'historical-source-identity-supplement',schedulerImplementationSha256:'source-classification-scheduler',failureImplementationSha256:'source-classification-failures'}))f[k]=c.protectedDependencies.files['scripts/lib/'+name+'.js'];
 return fixtureApi.sync(r);}
function matrix(){const r=synthetic(),rows=Object.entries(native.records).map(([name,record])=>({name,record,expected:true}));rows.push({name:'SYNTHETIC new issuer proof integrity, not real new acceptance',record:r,expected:true});
 for(const[name,mutate]of Object.entries({'new impl with old dependency':c=>c.protectedDependencies.files['scripts/lib/historical-source-taxonomy-classification-v3.js']=old.implementationSha256,'old impl with new dependency':c=>c.fingerprintInputs.implementationSha256=old.implementationSha256,'unknown impl':c=>c.fingerprintInputs.implementationSha256='0'.repeat(64),'unknown dependency map':c=>c.protectedDependencies.files['scripts/foreign.js']='0'.repeat(64),'unknown registry':c=>c.registrySha256='0'.repeat(64),'wrong projection':c=>c.fingerprintInputs.projectionSha256='0'.repeat(64),'controlled binding cannot borrow generic issuer':c=>c.source.currentPageClassificationBinding={contract:'controlled-current-page-classification-source-v2'}})){const copy=JSON.parse(JSON.stringify(r));mutate(copy.classificationRecord);rows.push({name,record:fixtureApi.sync(copy),expected:false});}
 return rows;}
function hugo(rows,profilesTemplate){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'multiissuer-hugo-')));try{fs.mkdirSync(path.join(dir,'data'));fs.mkdirSync(path.join(dir,'layouts'));fs.cpSync(path.join(repo,'layouts/partials'),path.join(dir,'layouts/partials'),{recursive:true});if(profilesTemplate)fs.writeFileSync(path.join(dir,'layouts/partials/taxonomy_classification_v3_profiles.html'),profilesTemplate);for(const n of['taxonomy-catalog','taxonomy-registry'])fs.copyFileSync(path.join(repo,'data',n+'.json'),path.join(dir,'data',n+'.json'));fs.writeFileSync(path.join(dir,'data/cases.json'),JSON.stringify(rows));fs.writeFileSync(path.join(dir,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\n');fs.writeFileSync(path.join(dir,'layouts/index.html'),'[{{ range $i,$r := hugo.Data.cases }}{{ if $i }},{{ end }}{{ dict "name" $r.name "accepted" (partial "taxonomy_source_only_v3_proof.html" $r.record) | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',dir,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});return JSON.parse(fs.readFileSync(path.join(dir,'public/index.html')));}finally{fs.rmSync(dir,{recursive:true,force:true});}}
const hd=p=>'(dict '+Object.entries(p).map(([k,v])=>JSON.stringify(k)+' '+JSON.stringify(v)).join(' ')+')';
test('original121 remains first byte-equivalent profile; new exact issuer keeps same FP23 and snapshot but only changes implementation/digest',()=>{
 assert.equal(old.implementationSha256,'140a343b457c3eb756f99df3d7323ad5a55245babf9733191a10d5151125726c');assert.equal(old.protectedDependencySha256,'1db887b14d10647b8770f32f238d6ce3f82dc0b8be86e16bebff749fae538655');
 assert.equal(fresh.implementationSha256,'254e837a5c5935b1c2722458e4dbdc7eb6a7ea13a769cc78a385d5e8a1604a0e');assert.equal(fresh.protectedDependencySha256,'39af4e78dee5b97eebcb11d2564ec9e8fb65e472afd83cf1c1aa880361963280');
 const {implementationSha256:oi,protectedDependencySha256:od,...a}=old,{implementationSha256:ni,protectedDependencySha256:nd,...b}=fresh;assert.deepEqual(a,b);assert.equal(Object.keys(synthetic().classificationRecord.fingerprintInputs).length,23);assert.equal(synthetic().classificationRecord.fingerprintInputs.model,'synthetic-test-model');
});
test('original121 subset9 remains exact; all native issuers pass source/current-page build preflight as records append',()=>{
 assert.equal(digest(JSON.stringify(native,null,2)+'\n'),'4bdbb659d0f9a5e0d7a68d4f4f7b07972fd63b6987f4bb2dab75859f60275607');assert.equal(Object.keys(native.records).length,9);
 for(const r of Object.values(nativeAll.records))assert.equal(api.validatePublicRecord(r,catalog.snapshots.find(s=>s.registrySha256===r.registrySha256)),true,r.paperId);
 assert.equal(require('../scripts/verify-taxonomy-v3').verify(repo).records,Object.keys(nativeAll.records).length);
});
test('two same-registry issuer tuples choose unique exact profile; JS and independent Hugo reject mixed/unknown/source-unsafe tuples',()=>{
 const rows=matrix();for(const row of rows){if(row.expected)assert.equal(api.validatePublicRecord(row.record,snapshot),true,row.name);else assert.throws(()=>api.validatePublicRecord(row.record,snapshot),undefined,row.name);}
 const results=hugo(rows);for(let i=0;i<rows.length;i++)assert.equal(results[i].accepted,rows[i].expected,rows[i].name);
});
test('duplicate exact approved tuple fails closed in JS and Hugo rather than silently taking first',()=>{
 const prior=profileModule.profiles;try{profileModule.profiles=[...prior,{...old}];assert.throws(()=>api.validatePublicRecord(Object.values(native.records)[0],snapshot),/唯一/);}finally{profileModule.profiles=prior;}
 const key=old.registrySha256+':'+old.implementationSha256+':'+old.protectedDependencySha256,template='{{ return dict '+JSON.stringify(old.registrySha256)+' '+hd(old)+' '+JSON.stringify(key)+' '+hd(old)+' }}';
 const result=hugo([{name:'duplicate approved issuer',record:Object.values(native.records)[0]}],template);assert.equal(result[0].accepted,false);
});
