'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),shared=require('../scripts/lib/tag-classification-v3-proof'),qualified=require('../scripts/lib/exact1028-qualified-classification'),proof=require('../scripts/lib/exact1028-review-proof');
const bytes=fs.readFileSync(path.join(root,'data/exact1028-qualified-classification.json')),q=shared.parseStrictJson(bytes.toString('utf8'));
test('actual independently qualified primary, old tuple and current page pass without native accepted cache',()=>{const r=qualified.read(root),p=r.resolve(q.pages[0].pagePath);assert.equal(p.researchType,'evaluation');assert.equal(p.primaryResearchRole.conceptId,'research_focus.robustness');assert.equal(p.classificationContract,qualified.CONTRACT);assert.equal(r.qualification.originalNativeStatus.accepted,0);assert.equal(r.resolve('content/posts/foreign.md'),null);assert.equal(proof.readBytes(bytes,{parseStrictJson:shared.parseStrictJson}).independentReviewQualified,true);});
test('closed qualification rejects altered file/old tuple/source/primary/ID mapping and false four gate',()=>{for(const change of[x=>x.paperId='foreign',x=>x.source.textSha256='0'.repeat(64),x=>x.originalNativeStatus.accepted=1,x=>x.publicationAuthority.predecessor.classificationRecordSha256='0'.repeat(64),x=>x.originalPrimary.decision.researchType='engineering']){const x=structuredClone(q);change(x);assert.throws(()=>proof.readBytes(Buffer.from(JSON.stringify(x)),{parseStrictJson:shared.parseStrictJson}));assert.throws(()=>qualified.validate(x));}
 const raw=JSON.parse(q.independentReview.responseText);raw.verifiedChecks.methodRole=false;const x=structuredClone(q);x.independentReview.responseText=JSON.stringify(raw);x.independentReview.responseSha256=proof.sha(x.independentReview.responseText);assert.throws(()=>proof.validate(x,{parseStrictJson:shared.parseStrictJson}));
 const duplicate=structuredClone(q);duplicate.independentReview.responseText=duplicate.independentReview.responseText.replace('{"accepted": true,','{"accepted": false, "accepted": true,');duplicate.independentReview.responseSha256=proof.sha(duplicate.independentReview.responseText);assert.throws(()=>proof.validate(duplicate,{parseStrictJson:shared.parseStrictJson}));
});
test('actual independent raw ID-to-literal replay agrees in Node and Hugo for eight rehashed negative cases',t=>{
 const changes={actual:()=>{},control:x=>x.raw.counterEvidenceResolution.items[0].rationale+='\f',wrongID:x=>x.raw.counterEvidenceResolution.items[0].sourceQuoteID='source:foreign',missing:x=>x.raw.counterEvidenceResolution.items.pop(),duplicate:x=>x.raw.counterEvidenceResolution.items[1]=structuredClone(x.raw.counterEvidenceResolution.items[0]),unanswered:x=>x.raw.counterEvidenceResolution.items[0].answered=false,falseGate:x=>x.raw.verifiedChecks.methodRole=false,window:x=>x.q.independentReview.sourceWindows['source:w1'].quote+='bad',primary:x=>x.q.originalPrimary.decision.primaryMethodId='method.attention'};
 const rows=Object.entries(changes).map(([name,change])=>{const x={q:structuredClone(q),raw:JSON.parse(q.independentReview.responseText)};change(x);x.q.independentReview.responseText=JSON.stringify(x.raw);x.q.independentReview.responseSha256=proof.sha(x.q.independentReview.responseText);let valid;try{proof.validate(x.q,{parseStrictJson:shared.parseStrictJson});valid=true;}catch{valid=false;}assert.equal(valid,name==='actual',name);return{name,q:x.q,expected:valid};});
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'exact1028-qualified-hugo-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'data'));fs.mkdirSync(path.join(dir,'layouts'));fs.cpSync(path.join(root,'layouts/partials'),path.join(dir,'layouts/partials'),{recursive:true});fs.writeFileSync(path.join(dir,'data/cases.json'),JSON.stringify(rows));fs.writeFileSync(path.join(dir,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\n');fs.writeFileSync(path.join(dir,'layouts/index.html'),'[{{ range $i,$r := hugo.Data.cases }}{{ if $i }},{{ end }}{{ dict "name" $r.name "accepted" (partial "exact1028_qualified_review.html" $r.q) | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',dir,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});JSON.parse(fs.readFileSync(path.join(dir,'public/index.html'))).forEach((r,i)=>assert.equal(r.accepted,rows[i].expected,r.name));
});
