'use strict';
// Real native/exported records only. Mutations stay in memory and never become
// data or issuer evidence. These gates also remain valid as the collection grows.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const api=require('../scripts/lib/taxonomy-v2-proof'),{seal}=require('./fixtures/taxonomy-v2-public');
const history=require('../data/taxonomy-history-v2.json'),catalog=require('../data/taxonomy-catalog.json'),core=require('../assets/js/taxonomy-core'),graph=core.createRegistry(require('../data/taxonomy-registry.json'),catalog);
const dispatcher=require('../scripts/lib/taxonomy-public-proof'),baselinePins=require('./fixtures/published1492-ordered-record-pins.json'),originalPages=new Set(baselinePins.records.map(r=>r.pagePath));
const na=Object.values(history.records).find(r=>r.paperId==='arxiv:2606.26348');
test('formal generic increments replay all source proofs and type-aware roles without forcing tasks or methods',()=>{
 assert.equal(history.contract,'historical-source-taxonomy-supplement-v2');const types=new Set();assert.equal(originalPages.size,1492);assert.deepEqual(Object.keys(history.records).slice(0,1492),baselinePins.records.map(r=>r.pagePath));for(const [pagePath,r] of Object.entries(history.records)){const snapshot=catalog.snapshots.find(s=>s.registrySha256===r.registrySha256);if(originalPages.has(pagePath)){assert.equal(api.validatePublicRecord(r,snapshot),true,r.paperId);}else{assert.equal(r.registrySha256,require('../scripts/lib/taxonomy-v2-371-proof').profile.registrySha256);assert.equal(dispatcher.validatePublicRecord(r,snapshot),true,r.paperId);}types.add(r.researchType);if(r.researchType!=='engineering'){assert.equal(r.primaryTaskId,'');assert.equal(r.primaryTaskLabel,'');}if(r.methodNotApplicable){assert.equal(r.primaryMethodId,null);assert.equal(r.primaryMethodLabel,'');assert.ok(!r.concepts.some(c=>c.facet==='method'));}}
 for(const type of ['engineering','science','analysis','evaluation','resource','position'])assert.ok(types.has(type),type);
});
test('real 26348 full-source NA replays 14582 UTF16 units and 22 spans; rehashed omissions or invented method reject',()=>{
 assert.ok(na);assert.equal(na.researchType,'position');assert.equal(na.domainScope,'out-of-domain');assert.equal(na.methodNotApplicable,true);assert.equal(na.primaryResearchRole.kind,'research_focus');assert.equal(na.primaryMethodId,null);const e=na.classificationRecord.naFullSourceEvidence;assert.equal(e.sourceChars,14582);assert.equal(e.snippets.length,22);assert.equal(e.sampling,'full-source');
 for(const mutate of [r=>r.classificationRecord.naFullSourceEvidence.snippets.pop(),r=>r.classificationRecord.naFullSourceEvidence.snippets[21].quoteEnd--,r=>r.classificationRecord.naFullSourceEvidence.sampling='balanced-spans',r=>r.classificationRecord.naFullSourceEvidence.sourceChars--,r=>r.primaryMethodId='method.attention']){const r=structuredClone(na);mutate(r);seal(r);assert.throws(()=>api.validatePublicRecord(r,catalog.snapshots.find(s=>s.registrySha256===r.registrySha256)));}
});
test('Hugo independently accepts every formal generic record and rejects rehashed real NA truncation',t=>{
 const repo=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'formal-generic-v2-hugo-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'data'));fs.mkdirSync(path.join(dir,'layouts'));fs.cpSync(path.join(repo,'layouts/partials'),path.join(dir,'layouts/partials'),{recursive:true});for(const name of ['taxonomy-catalog','taxonomy-registry'])fs.copyFileSync(path.join(repo,'data',name+'.json'),path.join(dir,'data',name+'.json'));
 const cases=Object.values(history.records).map(record=>({name:record.paperId,record,expected:true}));const bad=structuredClone(na);bad.classificationRecord.naFullSourceEvidence.snippets.pop();seal(bad);cases.push({name:'real NA truncated and rehashed',record:bad,expected:false});fs.writeFileSync(path.join(dir,'data/cases.json'),JSON.stringify(cases));fs.writeFileSync(path.join(dir,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section, taxonomy, term, RSS, sitemap, robotsTXT, "404"]\n');fs.writeFileSync(path.join(dir,'layouts/index.html'),'[{{ range $i,$c := hugo.Data.cases }}{{ if $i }},{{ end }}{{ dict "name" $c.name "accepted" (partial "taxonomy_source_only_v2_proof.html" $c.record) | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',dir,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});const result=JSON.parse(fs.readFileSync(path.join(dir,'public/index.html')));result.forEach((r,i)=>assert.equal(r.accepted,cases[i].expected,r.name));
});
