'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),pack=require('../scripts/lib/fullsite-taxonomy-pack'),selection=require('../scripts/lib/fullsite-publication-selection');
const history=pack.reconstruct(JSON.parse(fs.readFileSync(root+'/data/fullsite-taxonomy-history.json')),k=>fs.readFileSync(root+'/static/'+k));
const heldPath=Object.keys(history.records).find(p=>history.records[p].paperId===selection.HELD);
function fixture(){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fullsite-selection-hugo-'));fs.mkdirSync(dir+'/layouts/_default',{recursive:true});fs.mkdirSync(dir+'/data');fs.mkdirSync(dir+'/static');
 fs.cpSync(root+'/layouts/partials',dir+'/layouts/partials',{recursive:true});
 for(const n of ['taxonomy-catalog','taxonomy-registry','taxonomy-history','taxonomy-history-v2','current-page-taxonomy-history-v2','taxonomy-history-v3','fullsite-taxonomy-history','fullsite-taxonomy-admission','fullsite-taxonomy-sources','fullsite-taxonomy-publication-selection','taxonomy-old-v2-publication-holds'])if(fs.existsSync(root+'/data/'+n+'.json'))fs.copyFileSync(root+'/data/'+n+'.json',dir+'/data/'+n+'.json');
 fs.cpSync(root+'/static/fullsite-taxonomy',dir+'/static/fullsite-taxonomy',{recursive:true});fs.cpSync(root+'/data/taxonomy-snapshots',dir+'/data/taxonomy-snapshots',{recursive:true});
 const oldHold=JSON.parse(fs.readFileSync(root+'/data/taxonomy-old-v2-publication-holds.json'));const allPaths=Object.keys(history.records).concat(oldHold.rows.flatMap(r=>r.originalTuple.pages.map(p=>p.pagePath)));
 for(const p of allPaths){fs.mkdirSync(path.dirname(dir+'/'+p),{recursive:true});fs.copyFileSync(root+'/'+p,dir+'/'+p);}
 fs.writeFileSync(dir+'/hugo.yaml','baseURL: https://example.test/blog/\noutputs:\n  home: [HTML,JSON]\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\nmarkup:\n  goldmark:\n    renderer:\n      unsafe: true\n');
 fs.writeFileSync(dir+'/layouts/index.html','');fs.copyFileSync(root+'/layouts/_default/index.json',dir+'/layouts/_default/index.json');
 fs.writeFileSync(dir+'/layouts/_default/single.html','<script id="actual" type="application/json">{{ dict "proof" (partial "taxonomy_page_proof.html" .) "metadata" (partial "research_metadata.html" .) "valid" (partial "taxonomy_valid_records.html" .) "citation" (partial "citation_source.html" .) | jsonify | safeJS }}</script>{{ partial "paper_taxonomy.html" . }}');return dir;
}
function run(dir){return spawnSync('hugo',['--source',dir,'--noBuildLock','--panicOnWarning'],{encoding:'utf8'});}
function changeSelection(dir,mutate,repin=false){const file=dir+'/data/fullsite-taxonomy-publication-selection.json',s=JSON.parse(fs.readFileSync(file));mutate(s);const bytes=JSON.stringify(s)+'\n';fs.writeFileSync(file,bytes);if(repin){const p=dir+'/layouts/partials/taxonomy_fullsite_profiles.html';fs.writeFileSync(p,fs.readFileSync(p,'utf8').replaceAll('0449c97aae60c8ffc725e89ba964dcd87ecc752eb60111b9e7043954224d12bd',selection.sha(bytes)));}}
test('real Hugo checks all 300 originals, displays 299 and withholds one without legacy classification fallback',()=>{
 const dir=fixture();try{const result=run(dir);assert.equal(result.status,0,result.stderr);let eligible=0,held=0;
 for(const[p,r]of Object.entries(history.records)){const html=fs.readFileSync(dir+'/public/posts/'+path.basename(p,'.md')+'/index.html','utf8'),row=JSON.parse(html.match(/<script id="actual"[^>]*>([\s\S]*?)<\/script>/)[1]);if(r.paperId===selection.HELD){assert.equal(row.proof.publicationStatus,'withheld');assert(!row.proof.contract);assert.deepEqual(row.valid,[]);assert.equal(row.metadata.task,'');assert.equal(row.metadata.method,'');assert.equal(row.metadata.taxonomyPublicationStatus,'withheld');assert.equal(row.metadata.paperId,r.paperId);assert.equal(row.citation.url,history.classificationRecords[r.paperId].classificationRecord.source.sourceUrl);assert(html.includes('研究分类暂缓展示'));assert(!html.includes('class="paper-taxonomy"'));held++;}else{assert.equal(row.proof.proofSha256,r.proofSha256);assert.equal(row.proof.evidenceContract,r.contract);assert.deepEqual(row.metadata.primaryResearchRole,r.primaryResearchRole);eligible++;}}
 assert.equal(eligible,299);assert.equal(held,1);
 const entries=JSON.parse(fs.readFileSync(dir+'/public/index.json')),record=entries.find(r=>r.paperId===selection.HELD);assert(record);assert.equal(record.tagPublicationStatus,'withheld');assert.equal(record.tagContract,'');assert.deepEqual(record.tagConcepts,[]);assert.deepEqual(record.tags,[]);assert.equal(record.task,'');assert.equal(record.method,'');assert(!record.researchType);assert(!record.primaryResearchRole);
 const core=require('../assets/js/taxonomy-core'),graph=core.createRegistry(JSON.parse(fs.readFileSync(root+'/data/taxonomy-registry.json')),JSON.parse(fs.readFileSync(root+'/data/taxonomy-catalog.json')));assert.equal(graph.resolveRecord(record).status,'withheld');assert.deepEqual(core.groupPapers([record],graph)[0].conceptIds,[]);const md=require('../assets/js/reading-export').build([record],'md',{taxonomyGraph:graph}).text;assert(md.includes('暂无已核验的研究类型信息'));assert(!md.includes('研究类型与方向已核验'));
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('Hugo rejects unknown physical selection and re-signed wrong tuple or incomplete partition',()=>{
 const dir=fixture();const original=fs.readFileSync(dir+'/data/fullsite-taxonomy-publication-selection.json'),profiles=fs.readFileSync(dir+'/layouts/partials/taxonomy_fullsite_profiles.html');try{
 for(const [mutate,repin]of [[s=>{s.eligible[0].nativeProofSha256='0'.repeat(64);},false],[s=>{s.eligible[0].nativeProofSha256='0'.repeat(64);},true],[s=>s.eligible.pop(),true],[s=>s.eligible.reverse(),true],[s=>{s.withheld[0].reasonCode='approved';},true]]){fs.writeFileSync(dir+'/data/fullsite-taxonomy-publication-selection.json',original);fs.writeFileSync(dir+'/layouts/partials/taxonomy_fullsite_profiles.html',profiles);changeSelection(dir,mutate,repin);const r=run(dir);assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/publication selection.*rejected/);}
 // Remove one otherwise unchanged paper through a well-formed repack. Root
 // collection binding must reject it before a legacy fallback can be used.
 fs.writeFileSync(dir+'/data/fullsite-taxonomy-publication-selection.json',original);fs.writeFileSync(dir+'/layouts/partials/taxonomy_fullsite_profiles.html',profiles);
 const mf=dir+'/data/fullsite-taxonomy-history.json',m=JSON.parse(fs.readFileSync(mf)),last=m.shards[m.shards.length-1],shard=JSON.parse(fs.readFileSync(dir+'/static/'+last.path)),gone=shard.papers.pop(),removed=Object.keys(gone.pages).length;
 const b=JSON.stringify(shard)+'\n';m.paperCount--;m.recordCount-=removed;m.totalBytes+=Buffer.byteLength(b)-last.bytes;last.bytes=Buffer.byteLength(b);last.sha256=selection.sha(b);last.paperCount--;last.recordCount-=removed;last.path='fullsite-taxonomy/part-'+String(m.shards.length).padStart(4,'0')+'-'+last.sha256.slice(0,12)+'.json';fs.writeFileSync(dir+'/static/'+last.path,b);fs.writeFileSync(mf,JSON.stringify(m)+'\n');const dropped=run(dir);assert.notEqual(dropped.status,0);assert.match(dropped.stdout+dropped.stderr,/publication selection.*rejected/);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
test('withheld missing or drifted current MD must reject the whole original input gate',()=>{
 const dir=fixture(),original=fs.readFileSync(dir+'/'+heldPath);try{fs.unlinkSync(dir+'/'+heldPath);let r=run(dir);assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/publication selection.*rejected/);fs.writeFileSync(dir+'/'+heldPath,Buffer.concat([original,Buffer.from('\nChanged') ]));r=run(dir);assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/publication selection.*rejected/);}finally{fs.rmSync(dir,{recursive:true,force:true});}
});
