'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const repo=path.resolve(__dirname,'..'),api=require('../scripts/lib/fullsite-taxonomy-proof'),shared=require('../scripts/lib/taxonomy-classification-v3-proof'),pack=require('../scripts/lib/fullsite-taxonomy-pack'),review=require('../scripts/lib/fullsite-r6-review-proof');
const read=p=>fs.readFileSync(path.join(repo,p)),j=p=>shared.parseStrictJson(read(p).toString('utf8'));
function old(){return pack.reconstruct(j('data/fullsite-taxonomy-history.json'),p=>read('static/'+p));}
const six=j('data/fullsite-r6-corrections-history.json');
test('all six actual original objects, source/raw/four gates, current pages and exact predecessor authority pass',()=>{
 const packed=pack.reconstruct(j('data/fullsite-r6-corrections-packed.json'),p=>read('static/'+p));assert.equal(JSON.stringify(six),JSON.stringify(packed));assert.equal(Object.keys(six.records).length,6);
 const result=require('../scripts/lib/fullsite-r6-corrections').read(repo,old());assert.deepEqual(result.counts,{papers:6,pages:6});
 assert.equal(result.resolve('content/posts/absent.md'),null);for(const[p,r]of Object.entries(six.records)){assert.deepEqual(result.resolve(p),r);assert.equal(api.sha(read(p)),r.pageSha256);}
});
test('qualified review preserves original projection and strictly rejects missing/extra/source/window/rationale/flag mutations',()=>{
 const c=Object.values(six.classificationRecords).find(a=>a.paperId.endsWith('11461877')).classificationRecord;
 const original=JSON.parse(c.reviewResponseText);assert.deepEqual(review.project(c,original),c.reviewProof.response);
 const variants={extra:x=>x.raw.extra=null,missing:x=>delete x.raw.counterEvidenceResolution,packet:x=>x.raw.counterEvidenceResolution.packetSha256=api.sha('wrong'),source:x=>x.c.source.textSha256=api.sha('wrong'),window:x=>x.raw.counterEvidenceResolution.items.pop(),duplicate:x=>x.raw.counterEvidenceResolution.items[1]=structuredClone(x.raw.counterEvidenceResolution.items[0]),unanswered:x=>x.raw.counterEvidenceResolution.items[0].answered=false,rationaleQuote:x=>x.raw.counterEvidenceResolution.items[0].decisionRationaleQuote='This is fabricated decision rationale text.',counterQuote:x=>x.raw.counterEvidenceResolution.items[0].counterQuote='This is fabricated source counter evidence.',short:x=>x.raw.counterEvidenceResolution.items[0].rationale='short',control:x=>x.raw.counterEvidenceResolution.items[0].rationale+='\f',extraItem:x=>x.raw.counterEvidenceResolution.items[0].extra=true};
 for(const[name,mutate]of Object.entries(variants)){const x={c:structuredClone(c),raw:structuredClone(original)};mutate(x);x.c.reviewResponseText=JSON.stringify(x.raw);x.c.reviewProof.responseSha256=api.sha(x.c.reviewResponseText);assert.throws(()=>review.project(x.c,x.raw),undefined,name);}
 for(const k of ['researchType','domainScope','primaryResearchRole','methodRole']){const raw=structuredClone(original);raw.verifiedChecks[k]=false;const x=structuredClone(c);x.reviewResponseText=JSON.stringify(raw);x.reviewProof.responseSha256=api.sha(x.reviewResponseText);assert.notDeepEqual(review.project(x,raw),c.reviewProof.response,k);}
 const p=require('../scripts/lib/fullsite-taxonomy-profiles').profiles.at(-1);assert(review.isProfile(p));assert(!review.isProfile({...p,auditDependencySha256:api.sha('foreign')}));assert(!review.isProfile({...p,implementationFilePath:'scripts/fullsite-taxonomy-r4/fullsite-taxonomy-audit-classification.js'}));
});
test('actual six Hugo page metadata, citation, index, graph, four exports agree; separately qualified1028 retains its distinct contract',t=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'r6-six-actual-hugo-'));t.after(()=>{if(!process.env.R6_KEEP_MICRO)fs.rmSync(tmp,{recursive:true,force:true});});
 for(const d of ['data','layouts/_default','content/posts','static/fullsite-taxonomy'])fs.mkdirSync(path.join(tmp,d),{recursive:true});fs.cpSync(path.join(repo,'layouts/partials'),path.join(tmp,'layouts/partials'),{recursive:true});fs.cpSync(path.join(repo,'data'),path.join(tmp,'data'),{recursive:true});fs.cpSync(path.join(repo,'static/fullsite-taxonomy'),path.join(tmp,'static/fullsite-taxonomy'),{recursive:true});
 const held=j('data/taxonomy-old-v2-publication-holds.json').rows.find(r=>r.paperId.endsWith('11461028')).originalTuple.pages[0].pagePath;
 const paths=[...new Set([...Object.keys(old().records),...Object.keys(six.records),held])];for(const p of paths)fs.copyFileSync(path.join(repo,p),path.join(tmp,p));
 fs.copyFileSync(path.join(repo,'layouts/_default/index.json'),path.join(tmp,'layouts/_default/index.json'));
 fs.writeFileSync(path.join(tmp,'hugo.yaml'),'baseURL: https://example.test/blog/\nbuildFuture: true\nmarkup:\n  goldmark:\n    renderer:\n      unsafe: true\noutputs:\n  home: [HTML, JSON]\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\n');fs.writeFileSync(path.join(tmp,'layouts/index.html'),'');
 fs.writeFileSync(path.join(tmp,'layouts/_default/single.html'),'<script id="data" type="application/json">{{ dict "meta" (partial "research_metadata.html" .) "citation" (partial "citation_source.html" .) "proof" (partial "taxonomy_page_proof.html" .) | jsonify | safeJS }}</script>{{ partial "paper_taxonomy.html" . }}');
 execFileSync('hugo',['--source',tmp,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});
 const index=JSON.parse(fs.readFileSync(path.join(tmp,'public/index.json'))),graph=require('../assets/js/taxonomy-core').createRegistry(j('data/taxonomy-registry.json'),j('data/taxonomy-catalog.json')),exports=require('../assets/js/reading-export');
 for(const[p,r]of Object.entries(six.records)){
  const html=fs.readFileSync(path.join(tmp,'public/posts',path.basename(p,'.md'),'index.html'),'utf8'),row=JSON.parse(html.match(/<script id="data"[^>]*>([\s\S]*?)<\/script>/)[1]),c=six.classificationRecords[r.classificationRef].classificationRecord;
  assert.equal(row.proof.proofSha256,r.proofSha256);assert.equal(row.meta.researchType,c.researchType);assert.deepEqual(row.meta.primaryResearchRole,c.primaryResearchRole);assert.deepEqual(row.meta.classificationProvenance,c.source);assert.equal(row.citation.title,c.source.sourceTitle);assert.equal(row.citation.pdfUrl,c.source.pdfUrl||'');
  const e=index.find(x=>x.permalink.endsWith('/'+path.basename(p,'.md')+'/'));assert(e);assert.equal(e.tagProofSha256,r.proofSha256);assert.equal(graph.resolveRecord(e).status,'verified');for(const format of ['md','csv']){const out=exports.build([e],format,{tagGraph:graph}).text;assert(out.includes(c.primaryResearchRole.label));assert(out.includes('研究类型与方向已核验'));}for(const format of ['bib','ris'])assert(exports.build([e],format,{tagGraph:graph}).text.includes(c.source.sourceTitle));assert.equal(api.sha(read(p)),r.pageSha256);
 }
 const blocked=index.find(x=>x.permalink.endsWith('/'+path.basename(held,'.md')+'/'));assert.equal(blocked.researchType,'evaluation');assert.equal(blocked.tagClassificationContract,'exact1028-independent-review-qualified-classification-v1');assert.equal(graph.resolveRecord(blocked).status,'verified');
 const qp=require('../scripts/lib/exact1028-qualified-classification').read(repo).resolve(held),qh=fs.readFileSync(path.join(tmp,'public/posts',path.basename(held,'.md'),'index.html'),'utf8'),qr=JSON.parse(qh.match(/<script id="data"[^>]*>([\s\S]*?)<\/script>/)[1]);assert.equal(qr.proof.proofSha256,qp.proofSha256);assert.deepEqual(qr.meta.classificationProvenance,qp.source);assert.equal(qr.citation.title,qp.source.sourceTitle);for(const format of ['md','csv']){const out=exports.build([blocked],format,{tagGraph:graph}).text;assert(out.includes('鲁棒性'));assert(out.includes('评测研究'));assert(out.includes('研究类型与方向已核验'));}for(const format of ['bib','ris'])assert(exports.build([blocked],format,{tagGraph:graph}).text.includes(qp.source.sourceTitle));
 fs.writeFileSync(path.join(tmp,'seven-render-report.json'),JSON.stringify({contract:'seven-actual-correction-render-check-v1',pages:[...Object.entries(six.records).map(([p,r])=>({path:p,proof:r.proofSha256})),{path:held,proof:qp.proofSha256,contract:qp.classificationContract}],assertions:'actual page/source/citation/index/graph and four exports all passed',originalNative1028Accepted:0},null,2)+'\n');
 console.log('R6 actual micro rendered: '+tmp);
});
test('actual qualified review Node/Hugo mutation matrix preserves four-gate proof and closed packet semantics',t=>{
 const c=Object.values(six.classificationRecords).find(a=>a.paperId.endsWith('11461877')).classificationRecord,original=JSON.parse(c.reviewResponseText);
 const changes={original:()=>{},missing:x=>delete x.counterEvidenceResolution,unknown:x=>x.extra=null,badPacket:x=>x.counterEvidenceResolution.packetSha256=api.sha('bad'),unanswered:x=>x.counterEvidenceResolution.items[0].answered=false,missingWindow:x=>x.counterEvidenceResolution.items.pop(),unknownWindow:x=>x.counterEvidenceResolution.items[0].windowId='unapproved',nonLiteral:x=>x.counterEvidenceResolution.items[0].counterQuote='Fabricated source quote that is long enough.',nonDecision:x=>x.counterEvidenceResolution.items[0].decisionRationaleQuote='Fabricated decision quote that is long enough.',short:x=>x.counterEvidenceResolution.items[0].rationale='short',control:x=>x.counterEvidenceResolution.items[0].rationale+='\f',extraItem:x=>x.counterEvidenceResolution.items[0].extra=null};
 const rows=Object.entries(changes).map(([name,change])=>{const raw=structuredClone(original);change(raw);const classification=structuredClone(c);classification.reviewResponseText=JSON.stringify(raw);classification.reviewProof.responseSha256=api.sha(classification.reviewResponseText);let valid;try{review.project(classification,raw);valid=true}catch{valid=false}assert.equal(valid,name==='original',name);return{name,classification,raw,expected:valid};});
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'r6-review-hugo-'));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));for(const d of ['layouts','data'])fs.mkdirSync(path.join(tmp,d));fs.cpSync(path.join(repo,'layouts/partials'),path.join(tmp,'layouts/partials'),{recursive:true});fs.copyFileSync(path.join(repo,'data/fullsite-r6-counterevidence.json'),path.join(tmp,'data/fullsite-r6-counterevidence.json'));fs.writeFileSync(path.join(tmp,'data/cases.json'),JSON.stringify(rows));fs.writeFileSync(path.join(tmp,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\n');fs.writeFileSync(path.join(tmp,'layouts/index.html'),'[{{ range $i,$r := hugo.Data.cases }}{{ if $i }},{{ end }}{{ dict "name" $r.name "valid" ((partial "taxonomy_fullsite_r6_review.html" $r).valid) | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',tmp,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});const actual=JSON.parse(fs.readFileSync(path.join(tmp,'public/index.html')));for(let i=0;i<rows.length;i++)assert.equal(actual[i].valid,rows[i].expected,rows[i].name);
});
