'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const descriptor=require('../scripts/lib/fullsite-source-descriptor-proof'),title=require('../scripts/lib/fullsite-source-title-proof'),api=require('../scripts/lib/fullsite-taxonomy-proof'),{stableHash}=require('../scripts/lib/taxonomy-classification-v3-proof');
const samples=require('./fixtures/fullsite-source-descriptors.json');
function context(s){return{paperId:s.paperId,admission:{sourceAuthoritySha256:s.fullsiteSourceAuthority.authoritySha256,pages:s.currentPageSourceIdentity.pages},member:{sourceAuthoritySha256:s.fullsiteSourceAuthority.authoritySha256,sourceDescriptorSha256:stableHash(s)}};}
function rows(){const out=samples.samples.map((x,i)=>({name:'actual descriptor '+i+' '+x.paperId,source:x.source,context:context(x.source),expected:true}));
 const h=samples.samples.find(x=>x.source.kind==='fullsite-historical-direct-source-v1'&&x.source.paperId.startsWith('arxiv:')&&x.source.sourceVersion===null).source;
 const atom=samples.samples.find(x=>x.source.sourceTitleBinding?.contract==='official-arxiv-atom-title-bound-to-sealed-source-v1').source;
 const version=samples.samples.find(x=>x.source.sourceVersion).source;
 const native=samples.samples.find(x=>x.source.kind==='fullsite-native-conference-source-v1').source;
 const control=samples.samples.find(x=>x.source.fullsiteSourceAuthority.contract==='controlled-original-plan-source-v1').source;
 const conference=samples.samples.find(x=>x.source.originalSourceSeal).source;
 const negatives=[
 ['source optional null removed',h,s=>delete s.originalSourceSeal],['unknown source field',h,s=>s.invented=true],['PDF different paper',h,s=>s.pdfUrl='https://arxiv.org/pdf/2605.99999'],['title different text',h,s=>s.sourceTitle+=' changed'],['private path',h,s=>s.provenanceDisclosure='/private/tmp/source.txt'],['authority changed',h,s=>s.fullsiteSourceAuthority.authoritySha256=api.sha('wrong')],
 ['official title contract unknown',atom,s=>s.sourceTitleBinding.contract='manual-title'],['official title literal tampered',atom,s=>{s.sourceTitleBinding.titleQuote.quote+='!';s.sourceTitleBinding.titleQuote.quoteEnd++;s.sourceTitleBinding.titleQuote.quoteSha256=api.sha(s.sourceTitleBinding.titleQuote.quote);}],['official title incorrect UTF16 offset',atom,s=>s.sourceTitleBinding.titleQuote.quoteEnd++],['official metadata chronology invalid',atom,s=>s.sourceTitleBinding.observedAt='2027-02-30T00:00:00.000Z'],['official title claims old title authenticated',atom,s=>s.currentPageSourceIdentity.oldPublishedTitleAuthenticated=true],['official title wrong source text',atom,s=>s.sourceTitleBinding.sourceTextSha256=api.sha('wrong')],['official scalar surrogate',atom,s=>{const b=s.sourceTitleBinding;b.titleQuote.quote='&#55296;';b.titleQuote.quoteEnd=b.titleQuote.quoteStart+b.titleQuote.quote.length;b.titleQuote.quoteSha256=api.sha(b.titleQuote.quote);s.sourceTitle='\ufffd';b.sourceTitleSha256=api.sha(s.sourceTitle);s.currentPageSourceIdentity.sourceTitleSha256=api.sha(s.sourceTitle);}],
 ['rehashed fabricated 404',version,s=>{const v=s.sourceVersion;v.attemptedCurrentPdfStatus=200;const{identitySha256,...body}=v;v.identitySha256=stableHash(body);}],['nested version unknown field',version,s=>s.sourceVersion.extra=true],['nested version lost warning',version,s=>s.sourceVersion.warning=''],
 ['control arbitrary paper permission',control,s=>s.fullsiteSourceAuthority.controlledOriginalIntake.originItemSha256=api.sha('wrong')],['control reuse classification permission',control,s=>s.fullsiteSourceAuthority.controlledOriginalIntake.oldClassificationOrPublicationPermissionReused=true],['original seal wrong extraction count',conference,s=>s.originalSourceSeal.pdfExtractionsAtAdmission=1],['original seal changed text',conference,s=>s.originalSourceSeal.textSha256=api.sha('wrong')],
 ['native receipt different source',native,s=>s.originalSourceAuthorityReplay.pdfSha256=api.sha('wrong')],['native incorrect cache observation',native,s=>s.importedCacheObservation[0].matchesOriginal=!s.importedCacheObservation[0].matchesOriginal],['native extra cache observation',native,s=>s.importedCacheObservation.push(s.importedCacheObservation[0])],['native missing staging page',native,s=>s.stagingBindings.pop()],['native plan binding rehashed unknown field',native,s=>{s.planAuthorityBinding.invented=true;const{bindingSha256,...b}=s.planAuthorityBinding;s.planAuthorityBinding.bindingSha256=stableHash(b);}],['source nested shape not object',h,s=>s.fullsiteSourceAuthority=[]],
 ];
 // Explicit synthetic whitespace probes over a real shape. These do not
 // authenticate the changed quote against an actual sealed source.
 const foot=samples.samples.find(x=>x.source.paperId==='arxiv:2604.12455').source;
 for(const separator of ['\u00a0','\u1680','\u202f','\u3000','\ufeff','\u200b']){const source=JSON.parse(JSON.stringify(foot)),b=source.sourceTitleBinding;for(const q of [b.titleQuote,b.footnoteExclusion]){q.quote=q.quote.replace('Thanks:\u00a0','Thanks:'+separator);q.quoteSha256=api.sha(q.quote);}out.push({name:'synthetic ECMAScript whitespace U+'+separator.codePointAt(0).toString(16),source,context:context(source),expected:separator!=='\u200b'});}
 for(const[name,original,mutate]of negatives){const source=JSON.parse(JSON.stringify(original)),c=context(source);mutate(source);c.member.sourceDescriptorSha256=stableHash(source);out.push({name,source,context:c,expected:false});}return out;}
test('R2 actual 19 source descriptors and full-rehashed negative structure have identical JS/Hugo decisions',t=>{
 assert.equal(samples.semanticAccepted,false);const matrix=rows();for(const row of matrix){if(row.expected)assert.equal(descriptor.validate(row.source,row.context),true,row.name);else assert.throws(()=>descriptor.validate(row.source,row.context),undefined,row.name);}
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'fullsite-r2-source-hugo-'));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));fs.mkdirSync(path.join(tmp,'data'));fs.mkdirSync(path.join(tmp,'layouts'));fs.cpSync(path.join(__dirname,'../layouts/partials'),path.join(tmp,'layouts/partials'),{recursive:true});fs.writeFileSync(path.join(tmp,'data/cases.json'),JSON.stringify(matrix));fs.writeFileSync(path.join(tmp,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\n');fs.writeFileSync(path.join(tmp,'layouts/index.html'),'[{{ range $i,$c := hugo.Data.cases }}{{ if $i }},{{ end }}{{ dict "valid" (partial "research_fullsite_source_descriptor.html" $c) "warning" (partial "research_fullsite_source_warning.html" $c.source) | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',tmp,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});const rendered=JSON.parse(fs.readFileSync(path.join(tmp,'public/index.html')));for(let i=0;i<matrix.length;i++)assert.equal(rendered[i].valid,matrix[i].expected,matrix[i].name);
 const i=matrix.findIndex(x=>x.expected&&x.source.paperId==='arxiv:2604.14654');assert(i>=0);assert(rendered[i].warning.includes(matrix[i].source.sourceVersion.warning));assert(rendered[i].warning.includes(descriptor.ASSOCIATION));assert.equal(require('../scripts/lib/fullsite-taxonomy-profiles').profiles.some(p=>p.implementationSha256===api.sha('SYNTHETIC issuer')),false);
});
