'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),holds=require('../scripts/lib/tag-old-v2-publication-holds'),proof=require('../scripts/lib/tag-public-proof'),{stableHash}=require('../scripts/lib/tag-classification-v3-proof');
const bytes=fs.readFileSync(root+'/data/taxonomy-old-v2-publication-holds.json'),authority=JSON.parse(bytes),history=JSON.parse(fs.readFileSync(root+'/data/taxonomy-history-v2.json')),snapshots=new Map(JSON.parse(fs.readFileSync(root+'/data/taxonomy-catalog.json')).snapshots.map(s=>[s.registrySha256,s])),clone=x=>JSON.parse(JSON.stringify(x));
test('five real original V2 native/source/review/current-page proofs close before publication hold',()=>{
 const gate=holds.read(bytes,history);assert.equal(gate.withheldPapers,5);assert.equal(gate.withheldPages,5);
 for(const r of authority.rows)for(const p of r.originalTuple.pages){const record=history.records[p.pagePath];proof.validatePublicRecord(record,snapshots.get(record.registrySha256));const md=fs.readFileSync(root+'/'+p.pagePath,'utf8'),body=md.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/,'');assert.equal(cryptoSHA(md),record.pageSha256);assert.equal(cryptoSHA(body),record.bodySha256);assert.equal(gate.allows(p.pagePath,record),false);}
 const entry=Object.entries(history.records).find(([,r])=>!holds.IDS.includes(r.paperId));assert.equal(gate.allows(...entry),true);
 assert.equal(cryptoSHA(fs.readFileSync(root+'/data/taxonomy-history-v2.json')),authority.originalV2WholeFileSha256);
});
const cryptoSHA=x=>require('node:crypto').createHash('sha256').update(x).digest('hex');
test('altered whole tuple, removed original page, same-ID extra page and foreign authority fail closed',()=>{
 const p=authority.rows[0].originalTuple.pages[0].pagePath;
 for(const mutate of [h=>{delete h.records[p];},h=>{h.records[p].proofSha256='0'.repeat(64);},h=>{h.records[p].classificationRecord.fingerprintInputs.implementationSha256='0'.repeat(64);},h=>{h.records['content/posts/foreign-held.md']=clone(h.records[p]);}]){const h=clone(history);mutate(h);assert.throws(()=>holds.read(bytes,h),/rejected/);}
 const changed=clone(history),r=changed.records[p];r.pageKey='page:'+cryptoSHA('SYNTHETIC altered old page key');const body={...r};delete body.proofSha256;r.proofSha256=stableHash(body);proof.validatePublicRecord(r,snapshots.get(r.registrySha256));assert.throws(()=>holds.read(bytes,changed),/altered original tuple/);
 const a=clone(authority);a.rows.pop();assert.throws(()=>holds.read(Buffer.from(JSON.stringify(a)),history),/authority whole SHA/);const gate=holds.read(bytes,history);assert.throws(()=>gate.allows('content/posts/unknown.md',history.records[p]),/unknown/);
});
function fixture(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'old-v2-holds-hugo-'));fs.mkdirSync(d+'/layouts/_default',{recursive:true});fs.mkdirSync(d+'/data');fs.cpSync(root+'/layouts/partials',d+'/layouts/partials',{recursive:true});for(const n of ['taxonomy-registry','taxonomy-catalog','taxonomy-history','taxonomy-history-v2','current-page-taxonomy-history-v2','taxonomy-history-v3','taxonomy-old-v2-publication-holds'])fs.copyFileSync(root+'/data/'+n+'.json',d+'/data/'+n+'.json');fs.cpSync(root+'/data/taxonomy-snapshots',d+'/data/taxonomy-snapshots',{recursive:true});for(const row of authority.rows)for(const p of row.originalTuple.pages){fs.mkdirSync(path.dirname(d+'/'+p.pagePath),{recursive:true});fs.copyFileSync(root+'/'+p.pagePath,d+'/'+p.pagePath);}fs.writeFileSync(d+'/hugo.yaml','baseURL: https://example.test/\ndisableKinds: [section,taxonomy,term,RSS,sitemap,robotsTXT,"404"]\n');fs.writeFileSync(d+'/layouts/index.html','');fs.writeFileSync(d+'/layouts/_default/single.html','<script id="actual" type="application/json">{{ dict "proof" (partial "tag_page_proof.html" .) "metadata" (partial "research_metadata.html" .) "citation" (partial "citation_source.html" .) "valid" (partial "tag_valid_records.html" .) | jsonify | safeJS }}</script>{{ partial "paper_tags.html" . }}');return d;}
const run=d=>spawnSync('hugo',['--source',d,'--noBuildLock','--panicOnWarning'],{encoding:'utf8'});
test('Hugo five actual old V2 pages preserve source citations without verified classification fallback',()=>{
 const d=fixture();try{const r=run(d);assert.equal(r.status,0,r.stderr);for(const row of authority.rows)for(const p of row.originalTuple.pages){const html=fs.readFileSync(d+'/public/posts/'+path.basename(p.pagePath,'.md')+'/index.html','utf8'),actual=JSON.parse(html.match(/<script id="actual"[^>]*>([\s\S]*?)<\/script>/)[1]);assert.equal(actual.proof.publicationStatus,'withheld');assert(!actual.proof.contract);assert.deepEqual(actual.valid,[]);assert.equal(actual.metadata.tagPublicationStatus,'withheld');assert.equal(actual.metadata.task,'');assert.equal(actual.metadata.method,'');assert.equal(actual.metadata.paperId,row.paperId);assert.equal(actual.citation.url,history.records[p.pagePath].source.sourceUrl);assert.equal(actual.citation.pdfUrl,history.records[p.pagePath].source.pdfUrl);assert(html.includes('研究分类暂缓展示'));assert(!html.includes('class="paper-tags"'));}}finally{fs.rmSync(d,{recursive:true,force:true});}
});
test('Hugo unknown or altered held tuple and missing held page reject, even when other originals render',()=>{
 const d=fixture(),p=authority.rows[0].originalTuple.pages[0].pagePath;try{const h=clone(history);const body={...h.records[p],pageKey:'page:'+cryptoSHA('SYNTHETIC altered old page key')};delete body.proofSha256;h.records[p]={...body,proofSha256:stableHash(body)};proof.validatePublicRecord(h.records[p],snapshots.get(h.records[p].registrySha256));fs.writeFileSync(d+'/data/taxonomy-history-v2.json',JSON.stringify(h));let r=run(d);assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/old V2 publication hold.*rejected/);fs.copyFileSync(root+'/data/taxonomy-history-v2.json',d+'/data/taxonomy-history-v2.json');fs.unlinkSync(d+'/'+p);r=run(d);assert.notEqual(r.status,0);assert.match(r.stdout+r.stderr,/old V2 publication hold.*rejected/);}finally{fs.rmSync(d,{recursive:true,force:true});}
});
