'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync,spawnSync}=require('node:child_process');
const api=require('../scripts/lib/taxonomy-v2-proof'),na=require('../scripts/lib/taxonomy-na-full-source-proof'),cases=require('./fixtures/taxonomy-v3-public');
const repo=path.resolve(__dirname,'..');
test('public JS strictly replays V3/338/114 real native interface and synthetic version/NA negative cases',()=>{
 for(const c of cases.rows()){if(c.expected)assert.equal(api.validatePublicRecord(c.record,c.snapshot),true,c.name);else assert.throws(()=>api.validatePublicRecord(c.record,c.snapshot),undefined,c.name);}
});
test('Hugo applies the same V2/V3 profile,338 snapshot and formfeed/short-tail rules',t=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'blog-v3-hugo-'));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));fs.mkdirSync(path.join(tmp,'data'));fs.mkdirSync(path.join(tmp,'layouts'));fs.cpSync(path.join(repo,'layouts/partials'),path.join(tmp,'layouts/partials'),{recursive:true});for(const n of ['taxonomy-catalog','taxonomy-registry'])fs.copyFileSync(path.join(repo,'data',n+'.json'),path.join(tmp,'data',n+'.json'));const rows=cases.rows();fs.writeFileSync(path.join(tmp,'data/cases.json'),JSON.stringify(rows));fs.writeFileSync(path.join(tmp,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section, taxonomy, term, RSS, sitemap, robotsTXT, "404"]\n');fs.writeFileSync(path.join(tmp,'layouts/index.html'),'[{{ range $i,$case := hugo.Data.cases }}{{ if $i }},{{ end }}{{ dict "name" $case.name "valid" (partial "tag_source_only_v2_proof.html" $case.record) | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',tmp,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});const result=JSON.parse(fs.readFileSync(path.join(tmp,'public/index.html')));result.forEach((r,i)=>assert.equal(r.valid,rows[i].expected,r.name));
});
test('build entry rejects re-hashed unknown V3 profile before Hugo or public output mutation',t=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'blog-v3-preflight-'));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));fs.cpSync(path.join(repo,'scripts'),path.join(tmp,'scripts'),{recursive:true});fs.mkdirSync(path.join(tmp,'data'));fs.copyFileSync(path.join(repo,'data/taxonomy-catalog.json'),path.join(tmp,'data/taxonomy-catalog.json'));const row=cases.rows().find(c=>c.name==='unknown evidence contract');fs.writeFileSync(path.join(tmp,'data/taxonomy-history-v2.json'),JSON.stringify({contract:'historical-source-taxonomy-supplement-v2',records:{'content/posts/test-v3.md':row.record}}));const result=spawnSync(process.execPath,['scripts/build-site.js'],{cwd:tmp,encoding:'utf8'});assert.equal(result.status,1,result.stdout+result.stderr);assert.match(result.stderr,/profile/);assert.equal(fs.existsSync(path.join(tmp,'public')),false);
});
test('NA source coverage helper preserves V2 minimum length and rejects unknown contracts',()=>{
 const v3=cases.fixture({researchType:'position',na:true}).record.classificationRecord;assert.equal(na.validateNAFullSourceEvidence(v3,v3.source),true);const old=structuredClone(v3);old.evidenceSelectionContract='sealed-source-evidence-snippets-v2';assert.throws(()=>na.validateNAFullSourceEvidence(old,old.source),/编号顺序/);old.evidenceSelectionContract='unknown';assert.throws(()=>na.validateNAFullSourceEvidence(old,old.source),/未知编号/);
});

test('standalone NA helper rejects unknown non-NA selection with explicit null in JS and Hugo',t=>{
 const rows=['sealed-source-evidence-snippets-v2','sealed-source-evidence-snippets-v3-formfeed-split','unknown'].map(contract=>({classification:{methodNotApplicable:false,naFullSourceEvidence:null,evidenceSelectionContract:contract},source:{},expected:contract!=='unknown'}));
 for(const r of rows){if(r.expected)assert.equal(na.validateNAFullSourceEvidence(r.classification,r.source),true);else assert.throws(()=>na.validateNAFullSourceEvidence(r.classification,r.source),/未知编号/);}
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'blog-na-contract-'));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));fs.mkdirSync(path.join(tmp,'data'));fs.mkdirSync(path.join(tmp,'layouts/partials'),{recursive:true});fs.copyFileSync(path.join(repo,'layouts/partials/tag_na_full_source_proof.html'),path.join(tmp,'layouts/partials/tag_na_full_source_proof.html'));fs.writeFileSync(path.join(tmp,'data/cases.json'),JSON.stringify(rows));fs.writeFileSync(path.join(tmp,'hugo.yaml'),'baseURL: https://example.test/\ndisableKinds: [section, taxonomy, term, RSS, sitemap, robotsTXT, "404"]\n');fs.writeFileSync(path.join(tmp,'layouts/index.html'),'[{{ range $i,$case := hugo.Data.cases }}{{ if $i }},{{ end }}{{ partial "tag_na_full_source_proof.html" $case | jsonify | safeHTML }}{{ end }}]');execFileSync('hugo',['--source',tmp,'--noBuildLock','--panicOnWarning'],{stdio:'pipe'});assert.deepEqual(JSON.parse(fs.readFileSync(path.join(tmp,'public/index.html'))),[true,true,false]);
});
